
export const questions = {
    perspectiva: [
      "¿Qué importancia le das a la comunicación en las relaciones íntimas?",
      "¿Crees que la química sexual puede desarrollarse con el tiempo o es esencial desde el primer encuentro?",
      "¿Enamoramos del vínculo entre personas o de las personas en sí?",
      "¿Consideras que una vida sin actividad sexual es una vida insatisfactoria?",
      "¿Qué opinas sobre la idea de que tener sexo con empatía es exclusivo de las relaciones de pareja?",
      "¿Qué papel crees que juegan las fantasías en una relación sexual saludable?",
      "¿Cómo crees que influyen las expectativas sociales en nuestras actitudes hacia el sexo?",
      "¿Consideras que la monogamia es la única forma válida de relación?",
      "¿Qué opinas sobre la exploración y experimentación en la intimidad?",
      "¿Crees que la compatibilidad sexual es un factor fundamental en una relación?",
      "¿Cómo crees que la tecnología ha impactado nuestras relaciones sexuales y emocionales?",
      "¿Qué piensas acerca de la relación entre la confianza y la sexualidad?",
      "¿Cuál es tu perspectiva sobre la conexión emocional durante el sexo?",
      "¿Consideras que el amor y el deseo sexual son dos cosas separadas?",
      "¿Qué crees que define una buena comunicación sexual?",
      "¿Cómo influye la educación sexual que recibimos en nuestras actitudes y comportamientos?",
      "¿Qué opinas sobre la importancia del consentimiento en las relaciones sexuales?",
      "¿Crees que el género y la identidad sexual influyen en nuestras preferencias y experiencias?",
      "¿Qué piensas sobre el equilibrio entre el placer propio y el de la pareja en el sexo?",
      "¿Consideras que la intimidad emocional es más difícil de lograr que la intimidad física?",
      "¿Qué importancia le das a la comunicación sexual fuera del dormitorio?",
      "¿Crees que la vergüenza o la culpa pueden influir en nuestra experiencia sexual?",
      "¿Qué opinas sobre la idea de mantener la chispa sexual a lo largo del tiempo?",
      "¿Cómo influyen los valores culturales y religiosos en nuestras actitudes sexuales?",
      "¿Crees que el deseo sexual puede cambiar con la edad?",
      "¿Qué piensas sobre la importancia de la autoexploración sexual y el autoconocimiento?",
      "¿Consideras que el sexo es una forma de expresión emocional?",
      "¿Qué rol crees que juegan las fantasías en la vida sexual de una persona?",
      "¿Cómo afecta el estrés y las preocupaciones cotidianas a nuestra vida sexual?",
      "¿Crees que las expectativas sobre el cuerpo perfecto influyen en nuestras experiencias sexuales?",
      "¿Qué opinas sobre la idea de separar el sexo del amor en ciertos contextos?",
      "¿Consideras que la confianza en uno mismo es clave para una vida sexual satisfactoria?",
      "¿Cómo crees que influyen las redes sociales en nuestras percepciones de la sexualidad?",
      "¿Qué piensas sobre la comunicación sobre las preferencias y deseos sexuales en una relación?",
      "¿Crees que las diferencias culturales pueden influir en la manera en que vivimos la sexualidad?",
      "¿Qué importancia le das a la comunicación sobre la salud sexual y el uso de métodos de protección?",
      "¿Consideras que la aceptación y la autoestima influyen en la satisfacción sexual?",
      "¿Cómo crees que evolucionan las expectativas sexuales a lo largo de una relación?",
      "¿Qué opinas sobre la importancia de la honestidad en las conversaciones sobre el sexo?",
      "¿Crees que las fantasías sexuales pueden enriquecer una relación?",
      "¿Cómo afectan las experiencias pasadas nuestras actitudes y deseos sexuales?",
      "¿Qué piensas sobre la comunicación abierta en situaciones de disfunción sexual?",
      "¿Consideras que la comunicación sobre los límites y las preferencias sexuales es esencial?",
      "¿Crees que el consentimiento verbal es necesario en cada encuentro sexual?",
      "¿Qué opinas sobre la importancia de la educación sexual en la juventud?",
      "¿Cómo influyen los estereotipos de género en nuestras expectativas sexuales?",
      "¿Consideras que la sexualidad puede ser una forma de empoderamiento?",
      "¿Qué piensas sobre la influencia de la pornografía en nuestras percepciones del sexo?",
      "¿Crees que la comunicación sobre las fantasías sexuales puede fortalecer una relación?",
      "¿Cómo crees que las actitudes hacia el sexo han cambiado en la sociedad moderna?",
      "¿Cuál es tu visión ideal para el futuro?",
      "¿Qué crees que es lo más importante en la vida?",
      "Si pudieras hablar con tu yo del pasado, ¿qué consejo te darías?",
      "¿Cuál es el momento más importante que has experimentado hasta ahora?",
      "Si la vida fuese un libro, ¿cuál sería su título y por qué?",
      "Si fueras una obra de arte, ¿cómo te describirías?",
      "¿Qué crees que es más valioso: tiempo o dinero?",
      "Si tuvieras que escribir una carta a la humanidad, ¿qué les dirías?",
      "¿Qué es lo más hermoso que has encontrado en un lugar inesperado?",
      "Si pudieras ser una criatura mitológica, ¿cuál serías y por qué?",
      "¿Qué cambiarías en el mundo si tuvieras el poder para hacerlo?",
      "¿Cuál es el desafío más grande que has superado y cómo te cambió?",
      "Si pudieras vivir en una época histórica, ¿cuál elegirías y por qué?",
      "¿Cuál es tu definición personal de éxito y felicidad?",
      "Si pudieras tener una conversación con cualquier personaje histórico, ¿quién sería y qué le preguntarías?",
      "¿Qué lecciones has aprendido de tus mayores errores?",
      "Si pudieras aprender instantáneamente una habilidad, ¿cuál sería y por qué?",
      "¿Cuál es el lugar en el mundo donde te sientes más conectado/a contigo mismo/a?",
      "Si fueras un color, ¿cuál serías y cómo representaría tu personalidad?",
      "¿Qué te gustaría que las futuras generaciones recuerden de ti?",
      "Si pudieras tener una conversación con tu yo del futuro, ¿qué te gustaría preguntarle?",
      "¿Cuál es tu mayor temor y cómo lo enfrentas?",
      "Si pudieras visitar cualquier lugar en el universo, ¿a dónde irías y por qué?",
      "¿Qué opinas que es más importante: la verdad o la felicidad?",
      "Si pudieras experimentar un día en la vida de otra persona, ¿quién sería y por qué?",
      "¿Qué te hace sentir más vivo/a y enérgico/a?",
      "Si pudieras tener una habilidad sobrenatural, ¿cuál sería y cómo la usarías?",
      "¿Cuál es la canción que mejor representa tu estado emocional actual?",
      "Si pudieras revivir un solo día de tu vida, ¿cuál elegirías y por qué?",
      "¿Qué te inspira a superar los desafíos en tu vida?",
      "Si pudieras experimentar una cultura completamente diferente, ¿cuál elegirías y por qué?",
      "¿Qué libro o película ha tenido el mayor impacto en tu forma de pensar?",
      "Si pudieras tener una conversación con un animal, ¿cuál sería y qué le preguntarías?",
      "¿Qué te gustaría que la gente entendiera mejor sobre ti?",
      "Si pudieras cambiar una decisión que tomaste en el pasado, ¿cuál sería?",
      "¿Qué es lo que más valoras en tus amistades cercanas?",
      "Si pudieras explorar un lugar desconocido en la Tierra, ¿a dónde irías y qué descubrirías?",
      "¿Cuál es el mejor consejo que alguien te ha dado y cómo lo has aplicado?",
      "Si pudieras experimentar la vida en otro país, ¿cuál sería y qué te gustaría aprender?",
      "¿Qué te motiva a levantarte cada mañana y enfrentar el día?",
      "Si pudieras tener una conversación con una versión futura de ti mismo/a, ¿qué te gustaría saber?",
      "¿Qué aspecto de la naturaleza te conecta más con el mundo que te rodea?",
      "Si pudieras resolver un problema mundial, ¿cuál elegirías y cómo lo abordarías?",
      "¿Qué te hace sentir agradecido/a en tu vida en este momento?",
      "Si pudieras cambiar una creencia o opinión que tienes, ¿cuál sería y por qué?",
      "¿Qué te gustaría lograr en los próximos 5 años y cómo planeas hacerlo?",
      "Si pudieras viajar en el tiempo para presenciar un momento histórico, ¿cuál sería y por qué?",
      "¿Qué te hace sentir más conectado/a con la humanidad en general?",
      "Si pudieras experimentar un día en la vida de alguien que admiras, ¿quién sería y por qué?",
      "¿Qué te gustaría explorar o descubrir en el vasto universo?",
      "Si pudieras cambiar una cosa en la sociedad actual, ¿cuál sería y cómo lo lograrías?",
      "¿Qué mensaje o consejo te gustaría transmitir a las generaciones futuras?",
      "¿Cómo crees que tu vida sería diferente si hubieras tomado una decisión clave de manera distinta?", 
      "¿Qué crees que es lo más importante que has aprendido hasta ahora en la vida?", 
      "Si pudieras cambiar una creencia o valor que tienes, ¿cuál sería y por qué?", 
      "¿Cómo crees que tus amigos te perciben realmente?", 
      "Si pudieras ver el futuro, ¿qué te gustaría saber?", 
      "¿Qué harías diferente si supieras que nadie te juzgaría por ello?", 
      "¿Qué es lo que más valoras en las personas que te rodean?", 
      "Si pudieras cambiar una cosa sobre la sociedad, ¿qué sería?", 
      "¿Cómo crees que tus padres te ven en comparación con cómo te ves tú?", 
      "¿Qué tan diferente sería tu vida si no tuvieras miedo al fracaso?", 
      "Si pudieras regresar al pasado, ¿qué consejo te darías?", 
      "¿Qué es lo que más te preocupa sobre el futuro?", 
      "¿Cómo crees que te afecta lo que piensan los demás?", 
      "¿Qué crees que la gente nota primero sobre ti?", 
      "Si pudieras ser famoso por un día, ¿qué harías?", 
      "¿Qué es lo más importante que has aprendido de una experiencia dolorosa?", 
      "Si pudieras cambiar una sola cosa en tu vida, ¿qué sería y por qué?", 
      "¿Cómo te ves a ti mismo en comparación con cómo los demás te ven?", 
      "¿Qué crees que te motiva más, el amor o el miedo?", 
      "Si pudieras elegir cualquier talento para tener instantáneamente, ¿cuál sería?", 
      "¿Cómo crees que cambiaría tu vida si dejaras de preocuparte por el futuro?", 
      "¿Qué harías si tuvieras el poder de influir en la mente de las personas?", 
      "¿Qué piensas sobre la idea de que todo en la vida tiene un propósito?", 
      "¿Cómo cambiaría tu vida si nunca más pudieras mentir?", 
      "Si pudieras comunicarte con una versión más joven de ti, ¿qué le dirías?", 
      "¿Qué te hace sentir más vivo?", 
      "¿Qué crees que los demás podrían aprender de ti?", 
      "¿Qué significa para ti tener éxito en la vida?", 
      "Si pudieras ser recordado por una sola cosa, ¿qué sería?", 
      "¿Cómo crees que sería tu vida si hubieras nacido en otra parte del mundo?", 
      "¿Qué es lo que más te gusta de quién eres?", 
      "Si tuvieras la oportunidad de empezar de nuevo, ¿qué harías diferente?", 
      "¿Cómo crees que los demás te describen cuando no estás presente?", 
      "¿Qué es lo más importante que has aprendido sobre ti mismo?", 
      "Si pudieras vivir la vida de alguien más por un día, ¿quién sería y por qué?", 
      "¿Cómo crees que afectas a las personas a tu alrededor?", 
      "¿Qué crees que es lo más importante que puedes hacer en la vida?", 
      "¿Cómo te sentirías si todos conocieran tus secretos más profundos?", 
      "¿Qué es lo que más valoras en la vida?", 
      "Si pudieras cambiar una cosa en el mundo, ¿qué sería?", 
      "¿Qué crees que es lo que te define como persona?", 
      "¿Cómo te afecta lo que piensan los demás de ti?", 
      "Si pudieras hacer una pregunta al universo y obtener una respuesta, ¿cuál sería?", 
      "¿Cómo crees que serás recordado cuando ya no estés?", 
      "¿Qué crees que te impide alcanzar tu máximo potencial?", 
      "¿Cómo cambiaría tu vida si supieras que nunca serás juzgado?", 
      "¿Qué es lo que más te enorgullece de ti mismo?", 
      "Si pudieras eliminar todos tus recuerdos, ¿lo harías? ¿Por qué?", 
      "¿Qué harías si tuvieras todo el tiempo del mundo?",
      "¿Nos enamoramos del vínculo entre personas o de las personas en sí?",
      "¿Crees que la tecnología ha impactado nuestras relaciones sexuales y emocionales?",
      "¿Cuál es tu perspectiva sobre la conexión emocional durante el sexo?",
      "¿Cómo crees que las redes sociales han cambiado la forma en que nos relacionamos?",
      "¿El amor es una decisión o un sentimiento?",
      "¿Es posible amar a más de una persona al mismo tiempo?",
      "¿El concepto de 'alma gemela' es real o una ilusión?",
      "¿Qué impacto tiene la educación en nuestras relaciones personales?",
      "¿Qué pesa más en una relación: la confianza o la pasión?",
      "¿Es más importante la compatibilidad emocional o la atracción física?",
      "¿Cómo crees que el miedo influye en nuestras decisiones de vida?",
      "¿Hasta qué punto nuestras experiencias de infancia moldean quiénes somos?",
      "¿Se puede separar el amor de la atracción sexual?",
      "¿Es posible tener una amistad completamente desinteresada?",
      "¿Cuál crees que es el papel del ego en los conflictos interpersonales?",
      "¿Las relaciones a distancia pueden ser tan exitosas como las presenciales?",
      "¿Cuánto impacto tiene la cultura en nuestra percepción del amor?",
      "¿Es más importante encontrar a alguien compatible o aprender a adaptarse?",
      "¿Las personas realmente pueden cambiar o solo se adaptan temporalmente?",
      "¿Qué tan importante es la validación externa en nuestra autoestima?",
      "¿Crees que la monogamia es natural o una construcción social?",
      "¿Se puede amar sin apego?",
      "¿Es mejor arrepentirse de hacer algo o de no haberlo intentado?",
      "¿Cuánta influencia tiene el destino en nuestras vidas?",
      "¿La felicidad depende más de circunstancias externas o de nuestra actitud?",
      "¿Es posible vivir sin expectativas?",
      "¿Cómo afecta la vulnerabilidad a nuestras relaciones personales?",
      "¿Qué pesa más en una relación: la historia compartida o el presente?",
      "¿Es justo juzgar a alguien por su pasado?",
      "¿Las oportunidades en la vida son más cuestión de suerte o de esfuerzo?",
      "¿La sociedad nos empuja a encajar en moldes predefinidos?",
      "¿Cuál es el límite entre la admiración y la idealización?",
      "¿La moral es absoluta o relativa?",
      "¿Es posible vivir sin prejuicios?",
      "¿La madurez emocional viene con la edad o con la experiencia?",
      "¿Cómo influye el miedo al rechazo en nuestras decisiones?",
      "¿Hasta qué punto nuestras relaciones están influenciadas por nuestro entorno?",
      "¿El sufrimiento es necesario para crecer?",
      "¿Se puede ser completamente honesto sin herir a los demás?",
      "¿Cuál es el verdadero significado del éxito?",
      "¿Hasta qué punto somos responsables de nuestra propia felicidad?",
      "¿La inteligencia emocional es más importante que la inteligencia intelectual?",
      "¿Es mejor seguir la lógica o la intuición?",
      "¿Hasta qué punto el pasado define quiénes somos?",
      "¿El talento es innato o se desarrolla con el tiempo?",
      "¿Cómo afecta la gratitud a nuestra percepción de la vida?",
      "¿Es más importante la seguridad o la libertad?",
      "¿Cómo influye la autopercepción en la manera en que nos tratan los demás?",
      "¿Es posible encontrar un propósito universal en la vida?",
      "¿Cómo afecta la tecnología a nuestra capacidad de atención?",
      "¿El poder siempre corrompe?",
      "¿Hasta qué punto la justicia es subjetiva?",
      "¿La felicidad es un estado constante o momentos pasajeros?",
      "¿Cómo influye la autoaceptación en nuestras relaciones con los demás?",
      "¿Se puede aprender de los errores ajenos o solo de los propios?",
      "¿Es posible perdonar completamente a alguien?",
      "¿La empatía es una habilidad o una característica innata?",
      "¿Cuánto impacto tiene la música en nuestras emociones?",
      "¿Qué hace que una amistad sea realmente profunda?",
      "¿Es más importante la experiencia o la educación formal?",
      "¿Cómo influyen las expectativas en nuestra satisfacción con la vida?",
      "¿Es posible separar la razón de la emoción en la toma de decisiones?",
      "¿Es más valioso el amor propio o el amor hacia los demás?",
      "¿El miedo al fracaso nos protege o nos limita?",
      "¿Las emociones nublan o enriquecen nuestro juicio?",
      "¿Es mejor buscar la verdad o la paz?",
      "¿El lenguaje moldea nuestra forma de pensar?",
      "¿Cómo influye la percepción del tiempo en nuestra vida diaria?",
      "¿Es posible ser completamente objetivo?",
      "¿Cómo cambia nuestra percepción de la belleza con el tiempo?",
      "¿La intuición es más confiable que la lógica?",
      "¿Cómo afecta la rutina a nuestra creatividad?",
      "¿Las promesas siempre deben cumplirse?",
      "¿Qué pesa más en la vida: la razón o la pasión?",
      "¿Es mejor ser temido o amado?",
      "¿El dinero compra la felicidad o solo comodidad?",
      "¿La confianza se recupera después de ser traicionada?",
      "¿Cuánto de nuestras decisiones son realmente nuestras y no influenciadas por otros?",
      "¿Cómo influye la nostalgia en nuestra percepción del presente?",
      "¿Es mejor vivir con un propósito claro o explorar diferentes caminos?",
      "¿El amor a primera vista es real o una ilusión?",
      "¿Hasta qué punto podemos controlar nuestras emociones?",
      "¿La independencia emocional es necesaria para una relación sana?",
      "¿Cómo afecta el miedo a la soledad en nuestras elecciones sentimentales?",
      "¿Es posible desaprender creencias arraigadas?",
      "¿Es más importante la sinceridad o la amabilidad?",
      "¿La fama realmente hace feliz a la gente?",
      "¿Cómo cambia nuestra percepción del tiempo a medida que envejecemos?",
      "¿El amor se desgasta con el tiempo o evoluciona?",
      "¿Es mejor ser realista o soñador?",
      "¿Cómo influyen nuestras creencias en la forma en que interpretamos la realidad?",
      "¿Es posible cambiar radicalmente de personalidad?",
      "¿Hasta qué punto podemos conocer a alguien realmente?",
      "¿Es más valioso el conocimiento o la experiencia?",
      "¿Cómo influye la adversidad en nuestra identidad?",
      "¿Se puede encontrar sentido en el sufrimiento?",
      "¿Hasta qué punto es sano depender de otras personas?",
      "¿Es mejor la estabilidad o la emoción en la vida?",
      "¿Cómo afecta el entorno en nuestra capacidad de tomar decisiones?",
      "¿El pasado define nuestro futuro?",
      "¿La vida tiene un propósito o cada uno debe crear el suyo?",
      "¿El tiempo sana todas las heridas?",
      "¿Es más importante aprender del pasado o enfocarse en el presente?"
    ],
    profundidad: [
      "¿Qué es lo más valioso que has aprendido en la vida hasta ahora?",
      "Si pudieras hablar con tu yo de hace 10 años, ¿qué consejo le darías?",
      "¿Cuándo fue la última vez que sentiste una conexión profunda con alguien?",
      "¿Qué impacto crees que has tenido en la vida de otras personas?",
      "Si tuvieras que describir tu propósito en una sola frase, ¿cuál sería?",
      "¿Cuál ha sido el momento más transformador de tu vida?",
      "¿Cómo te gustaría ser recordado cuando ya no estés?",
      "¿Hay algo que nunca has dicho en voz alta por miedo a ser juzgado?",
      "¿Qué parte de tu vida cambiarías si pudieras hacerlo sin consecuencias?",
      "¿Cómo definirías la paz interior?",
      "¿Cuál ha sido la mayor lección que has aprendido del fracaso?",
      "Si hoy fuera tu último día de vida, ¿qué harías diferente?",
      "¿Qué significa para ti ser auténtico?",
      "¿Cuánto de lo que eres hoy es resultado de tus decisiones y cuánto de tu entorno?",
      "¿Cuál crees que es la mayor barrera que impide que las personas sean felices?",
      "¿Qué emociones te resulta más difícil expresar?",
      "¿Crees que existe una verdad absoluta o que todo es relativo?",
      "Si tu vida fuera un libro, ¿qué título tendría?",
      "¿Cuándo fue la última vez que sentiste un verdadero sentido de gratitud?",
      "¿Qué experiencia te ha cambiado la forma en la que ves la vida?",
      "¿Cómo gestionas el miedo a lo desconocido?",
      "Si pudieras resolver una sola duda existencial, ¿cuál sería?",
      "¿Cómo afecta tu pasado a la forma en que te relacionas con los demás?",
      "¿En qué aspectos sientes que aún no te conoces por completo?",
      "¿Qué significa para ti la libertad?",
      "Si pudieras experimentar la vida de otra persona por un día, ¿quién sería y por qué?",
      "¿Cuál es el miedo que más te ha limitado?",
      "¿Qué es lo más difícil de aceptar sobre ti mismo?",
      "¿Cómo defines la madurez emocional?",
      "¿Has sentido alguna vez que estabas en el camino equivocado en la vida?",
      "¿Qué crees que define el propósito de la vida?",
      "Si pudieras tener la respuesta a cualquier pregunta del universo, ¿cuál sería?",
      "¿Qué es lo más importante que has aprendido sobre el amor?",
      "¿Cómo manejas el sentimiento de soledad?",
      "¿Hay algo en tu vida que aún no has perdonado?",
      "¿Cuándo fue la última vez que te sentiste realmente en paz?",
      "Si pudieras revivir un solo día de tu vida, ¿cuál elegirías y por qué?",
      "¿Cómo te ha cambiado el dolor que has experimentado?",
      "¿Cuál es el mayor sacrificio que has hecho por alguien más?",
      "¿Qué harías si supieras que no puedes fallar?",
      "¿Cómo equilibras lo que quieres con lo que necesitas?",
      "¿Crees que el destino está escrito o que lo creamos con nuestras decisiones?",
      "¿Cuál es el mayor error que has cometido y qué aprendiste de él?",
      "¿Qué significa para ti la plenitud?",
      "¿Cómo te sientes respecto a la muerte?",
      "¿Qué te hace sentir verdaderamente vivo?",
      "¿Cómo diferencias entre lo que deseas y lo que realmente necesitas?",
      "¿Qué parte de tu personalidad crees que más ha evolucionado con los años?",
      "Si tuvieras que resumir tu vida en tres palabras, ¿cuáles serían?",
      "¿Qué te impide ser la mejor versión de ti mismo?",
      "¿Cómo defines el éxito en tu vida?",
      "¿Cuándo fue la última vez que hiciste algo solo por amor, sin esperar nada a cambio?",
      "Si pudieras borrar un recuerdo de tu vida, ¿cuál sería?",
      "¿Qué significa para ti la vulnerabilidad?",
      "¿Sientes que estás viviendo tu vida al máximo o que solo estás existiendo?",
      "¿Qué es lo que más valoras en una persona?",
      "¿Cuál es el mayor acto de valentía que has hecho?",
      "¿Cómo crees que la infancia moldea nuestra forma de amar?",
      "Si pudieras pasar una hora con cualquier persona, viva o muerta, ¿quién sería y por qué?",
      "¿Cuáles son las palabras que más te han marcado en la vida?",
      "¿Qué parte de tu vida sientes que no has explorado lo suficiente?",
      "¿Cuándo fue la última vez que te sentiste completamente libre?",
      "¿Cuánto peso le das a la opinión de los demás en tus decisiones?",
      "Si murieras mañana, ¿qué legado crees que dejarías?",
      "¿Qué te ha enseñado el sufrimiento?",
      "¿Cómo afecta el miedo al fracaso en la forma en que tomas decisiones?",
      "Si pudieras elegir una sola emoción para sentir por el resto de tu vida, ¿cuál sería?",
      "¿Qué significa para ti la espiritualidad?",
      "¿Sientes que eres una persona comprendida o que pocas personas te entienden realmente?",
      "¿Qué cosa nunca has dicho en voz alta pero te gustaría expresar?",
      "¿Cómo manejas la incertidumbre en tu vida?",
      "¿Qué es lo que más te ha sorprendido sobre ti mismo con el tiempo?",
      "¿Cuándo fue la última vez que hiciste algo que realmente te aterraba?",
      "Si pudieras cambiar un solo evento en la historia de la humanidad, ¿cuál sería?",
      "¿Qué harías diferente si supieras que nadie te juzgaría?",
      "¿Cómo ha cambiado tu percepción del tiempo a lo largo de tu vida?",
      "Si tuvieras que definir el significado del amor en una oración, ¿cuál sería?",
      "¿Cuál es la mentira más grande que te has dicho a ti mismo?",
      "¿Cómo manejas la sensación de no tener el control?",
      "¿Cuándo fue la última vez que te permitiste ser completamente vulnerable?",
      "Si pudieras escribir una carta a tu futuro yo, ¿qué le dirías?",
      "¿Qué te impide confiar completamente en los demás?",
      "¿Sientes que vives en el presente o que tu mente está en el pasado o el futuro?",
      "¿Cuál ha sido la conversación más profunda que has tenido con alguien?",
      "¿Crees que cada persona tiene un propósito en la vida o que lo construimos?",
      "¿Cuál es la mayor contradicción en tu forma de pensar?",
      "¿Cómo manejas el arrepentimiento?",
      "Si tuvieras que definir la vida con una sola metáfora, ¿cuál sería?",
      "¿Cuál es el consejo más valioso que has recibido?",
      "¿Cómo crees que te ha cambiado el amor?",
      "¿Qué es lo más importante que aún no has hecho en tu vida?",
      "Si hoy fuera el último día de la humanidad, ¿qué mensaje dejarías?",
      "¿Qué es lo que más te gustaría que la gente recordara de ti?",
      "¿Cuál es el miedo que más te gustaría superar?",
      "¿Qué te gustaría preguntarle a Dios o al universo si pudieras recibir una respuesta clara?",
      "¿Qué crees que hay después de la muerte?", 
      "¿Cuál es el mayor sacrificio que estarías dispuesto a hacer por alguien que amas?", 
      "¿Qué significa para ti la verdadera felicidad?", 
      "¿Cómo ha cambiado tu concepto de amor a lo largo de los años?", 
      "¿Qué impacto quieres dejar en el mundo antes de morir?", 
      "¿Qué es lo que te motiva a seguir adelante en los momentos difíciles?", 
      "¿Qué crees que te impide alcanzar tu máximo potencial?", 
      "Si pudieras vivir la vida de otra persona por un día, ¿quién sería y por qué?", 
      "¿Qué crees que es lo más importante en una relación?", 
      "¿Cómo te gustaría que te recordaran cuando ya no estés?", 
      "¿Qué es lo más importante que has aprendido sobre ti mismo?", 
      "¿Qué significa para ti ser auténtico?", 
      "¿Cuál es tu mayor miedo y cómo lo enfrentas?", 
      "¿Qué es lo que más te arrepientes de no haber hecho en la vida?", 
      "Si pudieras cambiar una sola cosa en tu pasado, ¿qué sería y por qué?", 
      "¿Qué es lo que más valoras en una amistad?", 
      "¿Cómo ha cambiado tu perspectiva sobre la vida con el tiempo?", 
      "¿Qué es lo más difícil que has tenido que superar?", 
      "¿Qué significa para ti la libertad?", 
      "¿Qué harías si supieras que te queda un año de vida?", 
      "¿Cuál es la lección más valiosa que has aprendido en la vida?", 
      "¿Qué es lo que te hace sentir más conectado con los demás?", 
      "¿Cómo defines el éxito en tu vida?", 
      "¿Qué es lo más importante que has hecho por otra persona?", 
      "¿Qué crees que es lo más difícil de ser humano?", 
      "¿Cómo ha influido tu infancia en la persona que eres hoy?", 
      "¿Qué es lo que más te preocupa sobre el futuro?", 
      "¿Cuál es tu mayor ambición en la vida?", 
      "¿Qué es lo que te da esperanza en los momentos oscuros?", 
      "¿Qué significa para ti tener un propósito en la vida?", 
      "¿Qué crees que te hace único?", 
      "¿Cómo ha cambiado tu idea de la felicidad a lo largo de los años?", 
      "¿Qué es lo que más te inspira en la vida?", 
      "¿Cuál es la decisión más difícil que has tomado?", 
      "¿Qué es lo que más valoras en ti mismo?", 
      "¿Qué crees que es lo más importante que puedes aprender en la vida?", 
      "¿Qué significa para ti vivir una vida plena?", 
      "¿Qué es lo más importante que puedes hacer por los demás?", 
      "¿Cuál es tu mayor fortaleza y cómo la has desarrollado?", 
      "¿Qué es lo que más te ha sorprendido de la vida?", 
      "¿Cómo ha cambiado tu perspectiva sobre el amor?", 
      "¿Qué es lo que más te motiva a ser una mejor persona?", 
      "¿Cuál es tu mayor pasión y cómo la persigues?", 
      "¿Qué es lo que más te ha enseñado la vida hasta ahora?", 
      "¿Cómo te gustaría que fuera tu legado?", 
      "¿Qué es lo que más te ha transformado como persona?", 
      "¿Qué significa para ti vivir con integridad?", 
      "¿Cómo has superado tus mayores desafíos en la vida?",
      "¿Cómo definirías la intimidad en una relación?",
      "¿Cuál es tu experiencia más significativa de conexión emocional con otra persona?",
      "¿Qué papel juegan la confianza y la vulnerabilidad en la intimidad?",
      "¿Cuál es el mayor obstáculo que enfrentas al abrirte emocionalmente a alguien?",
      "¿Cómo te sientes al compartir tus miedos e inseguridades con tu pareja?",
      "¿Cuál es el recuerdo más conmovedor que tienes de un momento íntimo?",
      "¿Qué piensas sobre la importancia de mantener la individualidad en una relación íntima?",
      "¿Cómo afecta el pasado emocional a tus relaciones actuales?",
      "¿Qué consideras que es esencial para construir una conexión profunda?",
      "¿Cuál es el mayor desafío que has enfrentado al comunicarte abiertamente en una relación?",
      "¿Cómo encuentras el equilibrio entre mantener secretos y ser completamente transparente?",
      "¿Cuál es el valor más profundo que buscas en una conexión íntima?",
      "¿Qué opinas sobre la idea de que la verdadera intimidad lleva tiempo en desarrollarse?",
      "¿Cómo manejas las diferencias en las necesidades de espacio y cercanía emocional?",
      "¿Qué te impulsa a revelar tus pensamientos más íntimos a tu pareja?",
      "¿Cuál ha sido tu experiencia más poderosa de superar obstáculos en una relación?",
      "¿Qué piensas sobre la idea de que la intimidad se relaciona con la aceptación incondicional?",
      "¿Cómo crees que la comunicación emocional afecta la calidad de una relación?",
      "¿Qué importancia le das a las conversaciones sobre el futuro en una relación íntima?",
      "¿Cuál es el mayor temor que tienes en cuanto a la intimidad?",
      "¿Cómo influyen las heridas emocionales pasadas en tus relaciones actuales?",
      "¿Qué papel juega el perdón en la construcción de la intimidad?",
      "¿Cómo crees que se puede mantener viva la chispa de la intimidad a lo largo del tiempo?",
      "¿Qué opinas sobre la idea de que la intimidad puede ser compartida con amigos cercanos además de parejas?",
      "¿Cómo te sientes al expresar tus deseos más profundos a tu pareja?",
      "¿Cuál es el mayor regalo que puedes dar a alguien en términos de intimidad?",
      "¿Cómo influyen las expectativas sobre la relación en la construcción de la intimidad?",
      "¿Qué piensas sobre la idea de que la intimidad implica aceptar tanto las fortalezas como las debilidades?",
      "¿Cuál ha sido la experiencia más valiosa que has tenido al permitirte ser vulnerable?",
      "¿Cómo crees que las experiencias compartidas fortalecen la intimidad en una relación?",
      "¿Qué importancia le das a la conexión espiritual en una relación íntima?",
      "¿Cómo enfrentas los desafíos de la distancia emocional en una relación?",
      "¿Qué papel juega la empatía en la construcción de la intimidad?",
      "¿Cuál ha sido tu mayor logro en términos de conectarte profundamente con alguien?",
      "¿Cómo crees que las barreras culturales pueden afectar la intimidad en una relación?",
      "¿Qué opinas sobre la idea de que la intimidad implica comprender los miedos y las esperanzas del otro?",
      "¿Cómo encuentras el equilibrio entre compartir y proteger tu privacidad emocional?",
      "¿Cuál ha sido tu experiencia más reveladora al permitirte ser vulnerable?",
      "¿Qué piensas sobre la importancia de nutrir la conexión emocional en una relación íntima?",
      "¿Cómo enfrentas las diferencias en la forma en que muestras cariño y afecto?",
      "¿Qué papel juegan las experiencias compartidas en la construcción de la intimidad?",
      "¿Cuál es tu perspectiva sobre cómo la intimidad puede cambiar y evolucionar con el tiempo?",
      "¿Cómo influyen las expectativas familiares en tu capacidad para conectarte profundamente?",
      "¿Qué opinas sobre la idea de que la intimidad se trata de conocer a alguien en su totalidad?",
      "¿Cómo enfrentas los momentos de desconexión emocional en una relación íntima?",
      "¿Qué papel desempeñan los desafíos compartidos en la construcción de una conexión profunda?",
      "¿Cuál es tu enfoque para superar las barreras emocionales en una relación?",
      "¿Cómo crees que la intimidad se relaciona con la autenticidad en una relación íntima?",
      "¿Qué opinas sobre la importancia de la gratitud en la construcción de la intimidad?",
      "¿Cómo enfrentas los momentos de vulnerabilidad en una relación íntima?",
      "¿Cuál ha sido el momento más significativo de tu vida?",
      "¿Qué experiencias te han cambiado como persona?",
      "¿Cuál es la lección más valiosa que has aprendido de tus fracasos?",
      "Si pudieras cambiar una decisión importante en tu vida, ¿cuál sería y por qué?",
      "¿Qué valores son fundamentales para ti y cómo influyen en tus decisiones?",
      "Si tuvieras que describirte en tres palabras, ¿cuáles usarías y por qué?",
      "¿Cuál es tu mayor miedo y cómo has tratado de superarlo?",
      "¿Qué crees que es la clave para una relación exitosa?",
      "Si pudieras conocer la respuesta a una pregunta sobre tu futuro, ¿cuál preguntarías?",
      "¿Cómo te enfrentas a los momentos de incertidumbre en tu vida?",
      "Si tu vida fuera una película, ¿cuál sería su mensaje central?",
      "¿Cuál es el desafío interno más grande que has superado y cómo lo lograste?",
      "¿Qué te ha enseñado el dolor y cómo ha impactado en tu crecimiento?",
      "Si pudieras cambiar una cosa sobre ti mismo/a, ¿qué sería y por qué?",
      "¿Cómo defines la autenticidad y cómo la vives en tu vida cotidiana?",
      "¿Qué opinas sobre el propósito de la existencia humana?",
      "Si tuvieras la oportunidad de influir en el mundo, ¿qué legado te gustaría dejar?",
      "¿Cuál es la relación más influyente que has tenido y cómo te ha afectado?",
      "¿Qué rol juega la empatía en tus relaciones personales?",
      "Si pudieras tener una conversación honesta contigo mismo/a, ¿qué te dirías?",
      "¿Cuál es la lección más importante que has aprendido de alguien menor que tú?",
      "¿Cómo manejas las contradicciones internas y las luchas emocionales?",
      "Si pudieras hablar con alguien que ya no está contigo, ¿qué les dirías?",
      "¿Cuál es tu filosofía personal sobre cómo vivir una vida plena?",
      "¿Qué te gustaría que las personas comprendieran mejor sobre tu mundo interior?",
      "Si tuvieras la oportunidad de cambiar una creencia global, ¿cuál sería y por qué?",
      "¿Qué te inspira a superar los obstáculos y perseverar en momentos difíciles?",
      "Si pudieras dar un consejo a tu yo más joven, ¿qué le dirías?",
      "¿Cómo encuentras el equilibrio entre la gratitud por el presente y la aspiración al futuro?",
      "¿Qué es lo que más te ha sorprendido en tu viaje de autodescubrimiento?",
      "Si tuvieras que definir el amor en una sola frase, ¿cómo lo describirías?",
      "¿Qué te motiva a seguir aprendiendo y creciendo a lo largo de tu vida?",
      "Si pudieras resolver un problema global, ¿cuál elegirías y cómo lo abordarías?",
      "¿Cuál es la mayor lección que has aprendido de una pérdida o separación?",
      "¿Cómo te conectas con tu intuición y confías en tus decisiones?",
      "Si pudieras enseñar una sola lección a la humanidad, ¿cuál sería?",
      "¿Cómo encuentras significado y propósito en los momentos difíciles?",
      "¿Qué papel juega la autenticidad en tus relaciones personales?",
      "Si pudieras experimentar la vida desde la perspectiva de otra persona, ¿quién sería?",
      "¿Cómo te enfrentas a tus propios prejuicios y sesgos?",
      "Si pudieras cambiar una política mundial, ¿cuál sería y cómo afectaría al mundo?",
      "¿Cómo defines la felicidad y qué haces para cultivarla en tu vida?",
      "Si tuvieras que describir tu evolución personal en una palabra, ¿cuál sería?",
      "¿Qué te gustaría explorar más profundamente en tu búsqueda de entendimiento?",
      "Si pudieras hacer una pregunta al universo y obtener una respuesta, ¿qué preguntarías?",
      "¿Cuál es la mayor lección que has aprendido al enfrentarte a tus miedos?",
      "¿Cómo influye tu pasado en tus elecciones y acciones actuales?",
      "Si pudieras resumir tu filosofía de vida en una frase, ¿cuál sería?",
      "¿Cómo te conectas con tu espiritualidad o sentido de trascendencia?",
      "Si pudieras hablar con alguien famoso, ¿qué conversación te gustaría tener?",
      "¿Cómo te imaginas tu vida en un estado de plenitud absoluta?",
      "Si tuvieras que compartir una sabiduría con las generaciones futuras, ¿cuál sería?"
    ],
    picantes: [
      ,  "¿Cuál es la fantasía más loca que has tenido pero nunca has contado?",
      "¿Alguna vez te han atrapado en una situación íntima? ¿Cómo fue?",
      "Si pudieras pasar una noche con cualquier persona del mundo, ¿quién sería?",
      "¿Qué es lo más atrevido que has hecho en un lugar público?",
      "¿Cuál es la experiencia más vergonzosa que has tenido en la cama?",
      "¿Alguna vez has fingido estar ocupado para evitar un encuentro íntimo?",
      "Si pudieras probar algo nuevo en la cama sin ser juzgado, ¿qué sería?",
      "¿Cuál ha sido tu peor encuentro sexual y por qué?",
      "¿Alguna vez te has sentido atraído por alguien inesperado, como un amigo cercano o un jefe?",
      "¿Has enviado alguna vez un mensaje subido de tono por error? ¿Cómo reaccionaste?",
      "¿Prefieres dominar o que te dominen?",
      "Si tuvieras que describir tu estilo en la cama con el nombre de una película, ¿cuál sería?",
      "¿Alguna vez has tenido un sueño erótico con alguien que te sorprendió?",
      "¿Cuál es la prenda de ropa que más te gusta ver en alguien?",
      "Si tuvieras que elegir entre nunca más tener sexo o nunca más besar, ¿qué elegirías?",
      "¿Qué parte de tu cuerpo crees que es la más atractiva?",
      "¿Te han pillado alguna vez viendo algo que no deberías? ¿Cómo reaccionaste?",
      "¿Has tenido alguna experiencia con alguien del mismo género?",
      "¿Alguna vez te has sentido atraído por la pareja de un amigo?",
      "¿Has usado juguetes en la cama? ¿Cuáles te gustaría probar?",
      "¿Prefieres hacerlo con las luces apagadas o encendidas?",
      "¿Cuál ha sido la propuesta más extraña que te han hecho en la cama?",
      "Si pudieras tener un superpoder en la cama, ¿cuál sería?",
      "¿Cuál es el peor beso que has dado?",
      "¿Alguna vez has tenido una aventura con alguien que no deberías?",
      "Si pudieras borrar una experiencia íntima de tu memoria, ¿cuál sería?",
      "¿Has tenido algún encuentro con alguien mucho mayor o mucho menor que tú?",
      "¿Qué es lo más salvaje que has hecho cuando estabas solo?",
      "Si pudieras ver los pensamientos más sucios de alguien por un día, ¿a quién elegirías?",
      "¿Alguna vez has mandado o recibido fotos subidas de tono?",
      "¿Has jugado con la idea de un trío o algo más atrevido?",
      "¿Qué es lo que más te excita en una persona?",
      "¿Qué piensas mientras lo haces?",
      "¿Prefieres la pasión intensa o la ternura en la cama?",
      "¿Te han hecho alguna propuesta indecente que rechazaste?",
      "¿Alguna vez te has sentido atraído por alguien completamente opuesto a tu tipo?",
      "¿Te gusta que te hablen sucio o prefieres el silencio?",
      "Si tuvieras que calificar tu desempeño en la cama del 1 al 10, ¿qué puntuación te darías?",
      "¿Qué es lo más loco que has hecho por deseo?",
      "¿Alguna vez has usado comida en el sexo?",
      "¿Te gusta experimentar o prefieres lo tradicional?",
      "Si pudieras revivir un encuentro íntimo, ¿cuál sería?",
      "¿Qué es lo más atrevido que te han dicho en la cama?",
      "¿Alguna vez has hecho el amor con alguien que apenas conocías?",
      "¿Has tenido una relación secreta o prohibida?",
      "¿Qué tan importante es la química en la cama para ti?",
      "¿Alguna vez has probado hacerlo en un lugar riesgoso?",
      "¿Cuál es la fantasía que más te gustaría cumplir?",
      "¿Has usado alguna vez lencería o disfraces en la cama?",
      "¿Qué palabra te enciende al escucharla en la cama?",
      "¿Has experimentado con ataduras o juegos de roles?",
      "¿Prefieres los encuentros espontáneos o los bien planeados?",
      "¿Cuál es el lugar más extraño donde lo has hecho?",
      "¿Te gusta tomar la iniciativa o prefieres que te guíen?",
      "¿Has tenido encuentros con más de una persona a la vez?",
      "¿Qué piensas de las relaciones abiertas?",
      "¿Alguna vez te han hecho una propuesta que te hizo dudar de inmediato?",
      "¿Qué opinas sobre los besos en lugares inesperados?",
      "¿Te han mandado mensajes picantes en un momento inoportuno?",
      "¿Te ha pasado que alguien quiera algo más serio después de un encuentro casual?",
      "¿Qué tipo de caricias te gustan más?",
      "Si pudieras tener una cita con un famoso solo por diversión, ¿a quién elegirías?",
      "¿Te ha gustado alguien solo por su forma de besar?",
      "¿Has intentado alguna vez grabarte en la intimidad?",
      "¿Crees que la química sexual puede superar la falta de compatibilidad emocional?",
      "¿Has usado alguna excusa para evitar un encuentro?",
      "¿Has sentido celos por la experiencia sexual de tu pareja?",
      "¿Alguna vez has hecho algo atrevido en una videollamada?",
      "¿Has compartido alguna vez un secreto íntimo con alguien inesperado?",
      "¿Qué tan importante es la pasión para ti en una relación?",
      "¿Prefieres encuentros intensos y cortos o largos y tranquilos?",
      "¿Alguna vez te has sentido inseguro en la cama?",
      "¿Te gusta jugar con el suspenso y la provocación antes del acto?",
      "¿Qué es lo que más disfrutas antes de empezar?",
      "¿Crees que la compatibilidad sexual es clave en una relación a largo plazo?",
      "¿Has tenido alguna vez un flechazo puramente físico?",
      "¿Has sentido atracción por alguien con quien no podías estar?",
      "¿Te atreverías a cumplir una fantasía de otra persona aunque no fuera tu estilo?",
      "¿Qué piensas del sexo casual?",
      "¿Has dejado alguna vez a alguien con ganas a propósito?",
      "¿Te excita más la imaginación o la realidad?",
      "¿Cuál es el límite que nunca cruzarías en la cama?",
      "¿Qué opinas sobre compartir detalles íntimos con amigos?",
      "¿Has sentido una atracción intensa por alguien en un solo momento?",
      "¿Crees que hay un número ideal de parejas en la vida?",
      "¿Cómo te sientes al hablar de tus gustos en la cama con una pareja?",
      "¿Te atreverías a hacer un reto extremo en la intimidad?",
      "¿Has sentido vergüenza después de un encuentro íntimo?",
      "¿Te han pedido alguna vez algo inesperado en la cama?",
      "¿Cómo te gusta que te seduzcan?",
      "¿Qué tipo de besos te vuelven loco?",
      "Si pudieras cambiar algo de tu historial íntimo, ¿qué sería?",
      "¿Crees que la conexión mental influye en la química física?",
      "¿Cuál es la mejor experiencia íntima que has tenido?",
      "¿Tienes una fantasía secreta que nunca has contado?",
      "¿Qué es lo más arriesgado que has hecho por deseo?",
      "¿Prefieres la aventura o la estabilidad en la intimidad?",
      "¿Cuál es la fantasía más oscura que has tenido y nunca has compartido?", 
      "¿Qué es lo más loco que has hecho por pura lujuria?", 
      "¿Si pudieras tener una aventura sin que nadie lo supiera, lo harías?", 
      "¿Cuál es el lugar más público donde has tenido relaciones?", 
      "¿Qué es lo más atrevido que te gustaría probar en la cama?", 
      "¿Cuál es la cosa más salvaje que has hecho en una noche de fiesta?", 
      "¿Alguna vez has sido infiel o lo has considerado seriamente?", 
      "¿Qué es lo más vergonzoso que has buscado en internet?", 
      "¿Te atrae alguien que no deberías, como el novio o novia de un amigo?", 
      "¿Cuál es tu recuerdo más picante de una aventura de una noche?", 
      "¿Qué parte de tu cuerpo te da más placer cuando es tocada?", 
      "¿Qué es lo más inapropiado que te excita?", 
      "¿Alguna vez has tenido pensamientos inapropiados sobre un colega?", 
      "¿Si pudieras pasar una noche con cualquier persona famosa, quién sería?", 
      "¿Te gustaría que te grabaran en un momento íntimo?", 
      "¿Qué es lo más atrevido que has hecho estando borracho?", 
      "¿Has usado alguna vez juguetes sexuales en tus encuentros?", 
      "¿Qué es lo más arriesgado que has hecho para satisfacer un deseo?", 
      "¿Alguna vez has tenido un sueño erótico con alguien inesperado?", 
      "¿Te gustaría cumplir alguna fantasía de dominación o sumisión?", 
      "¿Cuál es el lugar más inusual donde te has excitado?", 
      "¿Qué es lo más extremo que has hecho por placer?", 
      "¿Te has sentido atraído por alguien que está fuera de los límites?", 
      "¿Te gustaría experimentar algo más intenso o peligroso en el sexo?", 
      "¿Has tenido alguna fantasía sobre un amigo cercano?", 
      "¿Qué es lo más atrevido que has hecho mientras alguien podría haberte visto?", 
      "¿Qué es lo más cercano que has estado a ser atrapado en un momento íntimo?", 
      "¿Alguna vez has tenido una relación solo por el sexo?", 
      "¿Te excita la idea de ser sorprendido en un momento comprometedor?", 
      "¿Qué es lo más atrevido que has dicho en un mensaje de texto?", 
      "¿Te gustaría explorar el intercambio de parejas o algo similar?", 
      "¿Cuál es tu secreto más oscuro relacionado con el placer?", 
      "¿Has tenido alguna vez un deseo prohibido por alguien que no deberías?", 
      "¿Te atreverías a cumplir una fantasía en un lugar extremadamente público?", 
      "¿Qué es lo más atrevido que has hecho sin que nadie lo supiera?", 
      "¿Alguna vez has usado tu posición de poder para seducir a alguien?", 
      "¿Te gustaría probar algo que consideras tabú?", 
      "¿Has sentido alguna vez un deseo irresistible por alguien comprometido?", 
      "¿Cuál es la cosa más erótica que has visto en una película?", 
      "¿Qué es lo más atrevido que has hecho durante una videollamada?", 
      "¿Alguna vez has sentido una atracción física por alguien mucho mayor o menor?", 
      "¿Qué es lo más salvaje que has soñado hacer pero nunca te has atrevido?", 
      "¿Alguna vez has hecho algo arriesgado solo por la emoción del peligro?", 
      "¿Qué es lo más atrevido que te gustaría experimentar con otra persona?", 
      "¿Te has sentido atraído alguna vez por alguien que no encaja con tus gustos habituales?", 
      "¿Qué es lo más atrevido que harías si supieras que nadie se enteraría?", 
      "¿Alguna vez has compartido un secreto íntimo solo para seducir a alguien?", 
      "¿Qué es lo más salvaje que has hecho en una fiesta privada?",
      "Si tuvieras que crear una película erótica con tu vida, ¿cuál sería el argumento?",
      "¿Qué opinas sobre la idea de tener una noche de juegos de roles con tu pareja?",
      "Si pudieras experimentar una fantasía sensual en un lugar público, ¿dónde sería?",
      "¿Has probado alguna vez una experiencia sensual bajo la luz de la luna?",
      "Si tuvieras la oportunidad de explorar una fantasía prohibida, ¿cuál sería?",
      "¿Qué importancia le das al poder de la seducción en las relaciones?",
      "Si pudieras vivir una aventura ardiente en una época histórica, ¿cuál elegirías?",
      "¿Has experimentado con la idea de compartir tus pensamientos eróticos con tu pareja?",
      "Si pudieras crear tu propia guía de seducción, ¿qué consejos incluirías?",
      "¿Qué piensas sobre la posibilidad de tener una noche apasionada en un lugar exótico?",
      "Si pudieras tener una experiencia sensual en un escenario inusual, ¿cuál sería?",
      "¿Has explorado la idea de un fin de semana de pasión en un retiro romántico?",
      "Si pudieras protagonizar una escena ardiente de una película famosa, ¿cuál sería?",
      "¿Qué opinas sobre la posibilidad de sorprender a tu pareja con una fantasía secreta?",
      "Si pudieras revivir una experiencia erótica del pasado, ¿cuál elegirías?",
      "¿Has probado alguna vez la idea de una noche de pasión con elementos de misterio?",
      "Si pudieras explorar tus deseos más salvajes en un lugar remoto, ¿dónde sería?",
      "¿Qué importancia le das a la sensualidad en la construcción de una conexión emocional?",
      "Si pudieras protagonizar una sesión de fotos sensual, ¿en qué entorno sería?",
      "¿Has considerado la posibilidad de un encuentro erótico al estilo de una cita a ciegas?",
      "¿Cuál es tu fantasía más atrevida?",
      "Si pudieras tener una noche de pasión con una celebridad, ¿quién sería?",
      "¿Qué lugar inusual te gustaría probar para tener relaciones?",
      "¿Cuál es la situación más emocionante en la que has tenido relaciones?",
      "¿Tienes algún fetiche que te gustaría explorar?",
      "Si pudieras probar cualquier juguete sexual, ¿cuál elegirías?",
      "¿Qué opinas sobre el sexting y su papel en las relaciones modernas?",
      "¿Has tenido alguna experiencia en un lugar público o arriesgado?",
      "¿Qué te parece la idea de tener una noche temática con juegos sexuales?",
      "¿Cómo te sientes acerca de los juguetes y accesorios en la intimidad?",
      "¿Alguna vez has tenido un sueño erótico que te haya dejado impactado?",
      "Si pudieras cambiar de género por un día, ¿cómo explorarías tu sexualidad?",
      "¿Qué opinas sobre la posibilidad de tener encuentros casuales sin compromiso?",
      "¿Has experimentado con la seducción o el coqueteo en lugares inesperados?",
      "Si pudieras diseñar tu escenario perfecto para una noche apasionada, ¿cómo sería?",
      "¿Qué piensas sobre la idea de introducir alimentos en la intimidad?",
      "¿Cuál es tu opinión sobre el intercambio de roles en la pareja?",
      "Si pudieras recrear una escena de una película o libro en la vida real, ¿cuál sería?",
      "¿Qué crees que es lo más importante para mantener una chispa en la relación?",
      "¿Has probado alguna vez una experiencia de realidad virtual con contenido erótico?",
      "Si pudieras cambiar un aspecto de tu vida sexual, ¿qué elegirías?",
      "¿Qué opinas sobre el uso de disfraces en la intimidad?",
      "¿Alguna vez has considerado la posibilidad de tener relaciones en público?",
      "Si pudieras experimentar una noche de pasión en una época histórica, ¿cuál sería?",
      "¿Qué crees que es esencial para comunicar tus deseos y límites en la intimidad?",
      "¿Has explorado el mundo de los juegos de rol en la intimidad?",
      "Si pudieras cambiar un aspecto de las expectativas sexuales en la sociedad, ¿cuál sería?",
      "¿Qué opinas sobre la incorporación de juegos de mesa o cartas eróticas en la relación?",
      "¿Has explorado el concepto de 'amigos con beneficios' o relaciones sin compromiso?",
      "Si pudieras diseñar tu habitación de fantasía para una noche apasionada, ¿cómo sería?",
      "¿Qué importancia le das a la exploración de nuevas posiciones sexuales?",
      "¿Has tenido alguna experiencia en la que el factor sorpresa haya avivado la pasión?",
      "Si pudieras viajar en el tiempo y tener una noche íntima con alguien, ¿quién sería?",
      "¿Qué piensas sobre la posibilidad de combinar aventuras al aire libre con la intimidad?",
      "¿Has experimentado con la idea de un encuentro espontáneo en lugares públicos?",
      "Si pudieras cambiar un aspecto de las normas sexuales en la sociedad, ¿cuál sería?",
      "¿Qué opinas sobre la incorporación de elementos de BDSM en la intimidad?",
      "¿Has probado alguna vez una experiencia sensual en un lugar inusual?",
      "Si pudieras explorar cualquier lugar del mundo de manera íntima, ¿dónde sería?",
      "¿Qué importancia le das a la comunicación abierta sobre deseos sexuales?",
      "¿Has tenido alguna experiencia que te haya sorprendido por su intensidad?",
      "Si pudieras compartir una experiencia sensual con tu pareja ideal, ¿cómo sería?",
      "¿Qué te parece la idea de una escapada romántica con un toque picante?",
      "Si pudieras disfrutar de una noche apasionada en un destino exótico, ¿dónde sería?",
      "¿Has experimentado con la creación de un ambiente sensual a través de aromas?",
      "Si pudieras tener una cita temática con un enfoque sensual, ¿cómo sería?",
      "¿Qué opinas sobre el uso de la lencería y disfraces en la relación?",
      "Si pudieras revivir una experiencia pasional del pasado, ¿cuál sería?",
      "¿Has explorado la posibilidad de introducir elementos de juego en la intimidad?",
      "Si pudieras tener una noche apasionada en un lugar histórico, ¿dónde sería?"
    ],
    random: [
      "Si fueras un objeto inanimado por un día, ¿qué serías y por qué?",  
      "¿Cuál es el olor más raro que te gusta?",  
      "Si tuvieras que comunicarte solo con rimas por una semana, ¿cómo lo harías?",  
      "¿Qué nombre absurdo le pondrías a un restaurante de lujo?",  
      "Si pudieras añadir un día extra a la semana, ¿cómo lo llamarías y qué harías en él?",  
      "Si tuvieras que vivir en una época de la historia pero como un personaje de fondo, ¿cuál elegirías?",  
      "Si los animales pudieran hablar, ¿cuál crees que sería el más sarcástico?",  
      "¿Qué teoría conspirativa absurda te gustaría que fuera real?",  
      "Si pudieras ver un contador con un dato absurdo sobre tu vida, ¿qué dato te gustaría conocer?",  
      "Si los extraterrestres invadieran la Tierra, ¿cómo te ganarías su simpatía?",  
      "Si fueras a protagonizar una película de terror, ¿cuál sería el peor monstruo para enfrentarte?",  
      "Si tuvieras que reemplazar todas las bebidas del mundo con un solo líquido, ¿cuál sería?",  
      "Si pudieras crear un emoji que represente tu personalidad, ¿cómo sería?",  
      "Si los sueños tuvieran una banda sonora, ¿qué canción sonaría en los tuyos?",  
      "Si tuvieras que casarte con un alimento, ¿cuál sería y por qué?",  
      "Si la gravedad desapareciera por un día, ¿cómo crees que se vería el mundo?",  
      "Si los humanos evolucionaran para tener una nueva habilidad inútil, ¿cuál sería?",  
      "Si te despertaras como una estatua en una plaza, ¿cómo te asegurarías de hacer historia?",  
      "Si cada vez que hablaras sonara una melodía de fondo, ¿qué tipo de música sonarías?",  
      "Si tuvieras que cambiar tu nombre por el de un objeto, ¿cuál elegirías?",  
      "Si los memes se convirtieran en moneda, ¿cuál crees que tendría más valor?",  
      "Si tuvieras que hacer stand-up de un tema en el que no eres experto, ¿qué tema elegirías?",  
      "Si pudieras ser inmortal pero solo durante los fines de semana, ¿qué harías?",  
      "Si todos los colores tuvieran sabor, ¿a qué sabría el color azul?",  
      "Si las películas tuvieran olores, ¿cuál sería el peor olor que podrías experimentar?",  
      "Si te convirtieras en villano de una película, ¿cuál sería tu plan absurdo para conquistar el mundo?",  
      "Si fueras el director de tráfico del universo, ¿qué reglas extrañas implementarías?",  
      "Si tu sombra tuviera su propia personalidad, ¿cómo sería?",  
      "Si cada persona tuviera un superpoder ridículo, ¿cuál te gustaría que fuera el tuyo?",  
      "Si te despertaras con una voz famosa en lugar de la tuya, ¿cuál sería la mejor y la peor opción?",  
      "Si tu reflejo en el espejo empezara a actuar diferente a ti, ¿cómo reaccionarías?",  
      "Si pudieras añadir un nuevo signo del zodiaco basado en un animal raro, ¿cuál sería?",  
      "Si las estatuas cobraran vida una vez al año, ¿qué crees que harían?",  
      "Si los fantasmas fueran empleados de oficina, ¿qué tipo de quejas tendrían?",  
      "Si las redes sociales tuvieran sabor, ¿cómo sabría cada una?",  
      "Si las señales de tránsito dijeran la verdad sobre la vida, ¿qué mensajes tendrían?",  
      "Si las montañas fueran criaturas vivientes, ¿cómo crees que interactuarían con los humanos?",  
      "Si las nubes fueran comestibles, ¿a qué crees que sabrían?",  
      "Si te encontraras una puerta que lleva a un universo alternativo, ¿cuál sería tu primera acción?",  
      "Si tu perro o gato pudieran escribirte una carta, ¿qué crees que dirían?",  
      "Si los números de tu contraseña fueran una fecha importante en tu vida, ¿qué pasaría en esa fecha?",  
      "Si los videojuegos fueran realidades paralelas, ¿en cuál te gustaría vivir?",  
      "Si solo pudieras comunicarte a través de referencias a películas, ¿cómo te manejarías en la vida diaria?",  
      "Si los sueños tuvieran anuncios publicitarios, ¿qué tipo de comerciales aparecerían?",  
      "Si cada vez que chatearas se generara una factura, ¿cuánto deberías pagar?",  
      "Si las palabras que dijeras se convirtieran en objetos físicos, ¿qué desastre causarías?",  
      "Si tu nariz pudiera hacer algo más que oler, ¿qué habilidad elegirías?",  
      "Si los árboles pudieran hablar, ¿qué crees que dirían sobre la humanidad?",  
      "Si las plantas pudieran enviar mensajes de texto, ¿qué crees que escribirían?",  
      "Si los insectos tuvieran personalidad, ¿cuál sería el más molesto?",  
      "Si cada vez que lloraras lloviera en la vida real, ¿cómo afectaría el clima?",  
      "Si el tiempo pudiera pausarse a voluntad, ¿qué harías en esos momentos de pausa?",  
      "Si cada persona tuviera una intro musical al entrar a una habitación, ¿cuál sería la tuya?",  
      "Si las calles de tu ciudad cambiaran de lugar cada día, ¿cómo te adaptarías?",  
      "Si los planetas fueran personalidades humanas, ¿cómo describirías a cada uno?",  
      "Si te ofrecieran un millón de dólares pero con una maldición absurda, ¿cuál aceptarías?",  
      "Si pudieras cambiar el final de cualquier historia famosa, ¿cuál modificarías?",  
      "Si solo pudieras ver en blanco y negro pero con un color extra, ¿cuál elegirías?",  
      "Si los muebles de tu casa cobraran vida por un día, ¿cómo crees que se comportarían?",  
      "Si los espejos reflejaran cómo te sientes en lugar de cómo te ves, ¿cómo sería tu reflejo?",  
      "Si pudieras darle un nombre original a tu sombra, ¿cuál sería?",  
      "Si las luces del semáforo indicaran emociones en lugar de colores, ¿qué representarían?",  
      "Si cada vez que abrieras la puerta de tu casa aparecieras en un lugar diferente, ¿cómo lo manejarías?",  
      "Si te dieran la opción de hacer un documental sobre cualquier tema absurdo, ¿cuál elegirías?",  
      "Si los emojis fueran personas reales, ¿cuál sería el más insoportable?",  
      "Si cada vez que bostezaras hicieras un sonido raro, ¿qué sonido elegirías?",  
      "Si solo pudieras comer comidas que combinan dos sabores raros, ¿qué combinación harías?",  
      "Si los supermercados tuvieran laberintos secretos, ¿qué crees que habría dentro?",  
      "Si fueras una contraseña difícil de adivinar, ¿cómo sería tu combinación?",  
      "Si cada año de tu vida fuera un género de película, ¿cómo sería tu historia?",  
      "Si los dibujos que hiciste de niño cobraran vida, ¿qué estarían haciendo ahora?",  
      "Si existiera un planeta habitado solo por versiones alternativas de ti, ¿cómo sería?",  
      "Si las noticias fueran narradas por personajes de caricaturas, ¿quién sería el mejor presentador?",  
      "Si los relojes funcionaran a base de chistes, ¿cuánto tiempo crees que marcarían?",  
      "Si cada vez que dieras la mano a alguien intercambiaras recuerdos, ¿cómo lo usarías?",  
      "Si tu mejor idea solo viniera cuando estás en el baño, ¿cómo maximizarías tu creatividad?",  
      "Si tu risa tuviera efectos especiales, ¿qué sonido elegirías?"  ,
      "¿Qué sabor de helado describiría mejor tu personalidad?", 
      "Si fueras un animal, ¿cuál serías y por qué?", 
      "¿Qué superpoder ridículo te gustaría tener?", 
      "¿Qué harías si te despertaras siendo el género opuesto?", 
      "Si solo pudieras comer una cosa por el resto de tu vida, ¿qué sería?", 
      "¿Qué harías si te encontraras con un extraterrestre?", 
      "Si tuvieras que vivir en un videojuego, ¿cuál elegirías?", 
      "¿Qué harías si ganaras la lotería, pero solo pudieras gastar el dinero en cosas raras?", 
      "¿Qué harías si pudieras hablar con los animales?", 
      "Si pudieras tener un dinosaurio como mascota, ¿cuál elegirías?", 
      "¿Qué harías si te quedaras atrapado en un ascensor por 24 horas?", 
      "Si pudieras intercambiar vidas con una celebridad por un día, ¿quién sería?", 
      "¿Qué harías si pudieras ser invisible por un día?", 
      "¿Cuál es la cosa más extraña que te ha pasado en público?", 
      "¿Si fueras un fantasma, a quién asustarías primero?", 
      "Si pudieras ser cualquier personaje de una película, ¿quién serías?", 
      "¿Qué harías si un día descubrieras que tienes un gemelo malvado?", 
      "¿Qué harías si pudieras retroceder el tiempo 10 minutos?", 
      "Si fueras un vegetal, ¿cuál serías y por qué?", 
      "¿Qué harías si un día te convirtieras en tu personaje de dibujos animados favorito?", 
      "Si solo pudieras hablar en rimas, ¿cómo sonarías?", 
      "¿Cuál es la cosa más extraña que has comido y disfrutado?", 
      "¿Qué harías si te despertaras en el cuerpo de otra persona?", 
      "Si tuvieras que elegir un tema para tatuarte en la frente, ¿cuál sería?", 
      "¿Qué harías si pudieras cambiar tu nombre a cualquier cosa?", 
      "Si pudieras ser un superhéroe, pero solo podrías tener un poder inútil, ¿cuál sería?", 
      "¿Qué harías si tuvieras que elegir entre volar o respirar bajo el agua?", 
      "Si pudieras ser un maestro en cualquier actividad inútil, ¿cuál elegirías?", 
      "¿Qué harías si pudieras vivir dentro de una película animada?", 
      "Si solo pudieras escuchar una canción por el resto de tu vida, ¿cuál sería?", 
      "¿Qué harías si pudieras convertir cualquier objeto en oro?", 
      "Si pudieras tener un trabajo ridículo pero extremadamente bien pagado, ¿qué sería?", 
      "¿Qué harías si tuvieras que vivir en una isla desierta con solo un objeto?", 
      "Si pudieras vivir en cualquier época pasada, ¿cuál elegirías?", 
      "¿Qué harías si te encontraras con tu yo del futuro por 10 minutos?", 
      "Si tuvieras que elegir un nombre completamente nuevo, ¿cuál sería?", 
      "¿Qué harías si tuvieras que comunicarte solo a través de memes?", 
      "Si pudieras convertirte en un animal una vez al mes, ¿cuál sería?", 
      "¿Qué harías si pudieras borrar un evento de la historia?", 
      "Si pudieras tener un botón que te llevara a cualquier lugar del mundo, ¿dónde irías?", 
      "¿Qué harías si pudieras entender y hablar todos los idiomas del mundo?", 
      "Si fueras un objeto inanimado, ¿qué serías?", 
      "¿Qué harías si solo pudieras vestirte de un color para siempre?", 
      "Si pudieras tener un clon de ti mismo, ¿qué tarea le asignarías?", 
      "¿Qué harías si tuvieras que elegir entre ser siempre honesto o nunca poder mentir?", 
      "Si pudieras vivir en un libro, ¿en cuál sería?", 
      "¿Qué harías si pudieras hacer que todos olvidaran algo sobre ti?", 
      "Si pudieras ser un villano famoso por un día, ¿quién serías?", 
      "¿Qué harías si pudieras cambiar el final de cualquier película?", 
      "Si pudieras tener cualquier tipo de acento, ¿cuál elegirías?", 
      "¿Qué harías si pudieras eliminar un día de la semana?", 
      "Si fueras un personaje de videojuego, ¿cuál sería tu habilidad especial?", 
      "¿Qué harías si pudieras elegir cualquier profesión, pero solo por un día?", 
      "Si pudieras tener un canal de YouTube exitoso sobre cualquier tema, ¿cuál sería?", 
      "¿Qué harías si te convirtieras en el presidente de tu país por un día?", 
      "Si pudieras crear una ley ridícula que todos debieran seguir, ¿cuál sería?", 
      "¿Qué harías si un día descubrieras que puedes volar?", 
      "Si pudieras ser cualquier superhéroe, pero con un traje ridículo, ¿quién serías?", 
      "¿Qué harías si pudieras cambiar tu voz a la de cualquier persona famosa?", 
      "Si solo pudieras comer un tipo de comida por el resto de tu vida, ¿cuál sería?", 
      "¿Qué harías si te despertaras y todo estuviera al revés?", 
      "Si fueras una estación del año, ¿cuál serías?", 
      "¿Qué harías si pudieras visitar cualquier lugar en el universo?", 
      "Si pudieras ser un maestro de cualquier habilidad, pero nunca pudieras usarla, ¿cuál sería?", 
      "¿Qué harías si un día descubrieras que puedes leer mentes?", 
      "Si pudieras cambiar el clima a tu antojo, ¿qué elegirías?", 
      "¿Qué harías si te convirtieras en un meme viral?", 
      "Si solo pudieras tener una conversación por día, ¿con quién sería?", 
      "¿Qué harías si te encontraras con un doble exacto de ti mismo?", 
      "Si pudieras vivir en cualquier planeta del sistema solar, ¿cuál elegirías?", 
      "¿Qué harías si pudieras hacer que cualquier objeto cobre vida?", 
      "Si pudieras ser un experto en cualquier tema absurdo, ¿cuál sería?", 
      "¿Qué harías si solo pudieras usar una red social por el resto de tu vida?", 
      "Si fueras una bebida, ¿cuál serías y por qué?", 
      "¿Qué harías si pudieras cambiar el color del cielo a cualquier color?", 
      "Si pudieras tener cualquier trabajo sin ninguna habilidad previa, ¿cuál elegirías?", 
      "¿Qué harías si descubrieras que puedes controlar el tiempo?", 
      "Si pudieras transformar tu vida en un reality show, ¿cómo sería?", 
      "¿Qué harías si pudieras hacer que cualquier animal sea del tamaño de un perro?", 
      "Si pudieras vivir en cualquier parte del mundo sin preocuparte por el dinero, ¿dónde sería?", 
      "¿Qué harías si pudieras volver a vivir un solo día de tu vida?", 
      "Si pudieras cambiar tu estatura a voluntad, ¿cómo la usarías?", 
      "¿Qué harías si pudieras ver el futuro, pero solo un día por adelantado?", 
      "Si pudieras eliminar una cosa molesta de la vida diaria, ¿qué sería?", 
      "¿Qué harías si pudieras entender a las plantas?", 
      "Si pudieras tener una mascota legendaria de la mitología, ¿cuál sería?", 
      "¿Qué harías si pudieras cambiar el nombre de cualquier cosa en el mundo?", 
      "Si solo pudieras usar una palabra para describir todo, ¿cuál sería?", 
      "¿Qué harías si te convirtieras en el personaje principal de tu serie favorita?", 
      "Si pudieras cambiar cualquier parte de tu cuerpo al de un animal, ¿cuál sería?", 
      "¿Qué harías si te dieran la capacidad de caminar a través de las paredes?", 
      "Si pudieras vivir dentro de una pintura famosa, ¿cuál sería?", 
      "¿Qué harías si te convirtieras en un emoji?", 
      "Si pudieras ser cualquier objeto en una película, ¿qué serías?", 
      "¿Qué harías si pudieras cambiar cualquier ley física por un día?",
      "¿Cómo fue la primera vez que viste contenido para adultos? ¿En qué contexto fue?",
      "¿Alguna vez has tenido una conexión inesperada con una persona que acabas de conocer?",
      "Si pudieras tener una cita con alguien famoso, ¿quién sería y qué harían?",
      "¿Qué harías si te encontraras en una isla desierta con solo una persona por un mes?",
      "¿Tienes algún secreto extravagante o divertido que estés dispuesto a compartir?",
      "¿Cuál es la cosa más extraña que has hecho por amor?",
      "Si pudieras intercambiar de vida con alguien por un día, ¿quién sería y qué harías?",
      "¿Alguna vez has tenido un encuentro inesperado que cambió tu día por completo?",
      "Si fueras un superhéroe, ¿cuál sería tu súper poder y cómo lo usarías?",
      "¿Tienes una historia divertida o embarazosa que nunca olvidarás?",
      "Si pudieras vivir en cualquier época histórica, ¿cuál elegirías y por qué?",
      "¿Alguna vez has experimentado un flechazo a primera vista? Cuéntanos.",
      "Si pudieras crear una nueva tradición, ¿cuál sería y cómo la celebrarías?",
      "¿Tienes alguna habilidad o talento oculto que pocos conocen?",
      "Si pudieras tener una conversación con cualquier personaje histórico, ¿quién sería?",
      "¿Has tenido alguna experiencia que te haya hecho creer en el destino?",
      "Si pudieras viajar a cualquier lugar del mundo en este momento, ¿dónde irías?",
      "¿Tienes alguna meta o sueño que nunca has compartido con nadie?",
      "Si fueras el protagonista de una película, ¿cuál sería el género y el argumento?",
      "¿Alguna vez has tenido una intuición fuerte que resultó ser cierta?",
      "Si pudieras cambiar una decisión en tu pasado, ¿cuál sería y por qué?",
      "¿Tienes una historia de amistad que te haga sonreír cada vez que la recuerdas?",
      "Si fueras un animal, ¿cuál sería y cómo pasarías un día típico?",
      "¿Alguna vez has tomado una decisión impulsiva que cambió tu vida?",
      "Si pudieras presenciar un evento histórico, ¿cuál sería y por qué?",
      "¿Tienes alguna tradición familiar única o especial que te gustaría compartir?",
      "Si pudieras vivir en cualquier universo ficticio, ¿cuál sería tu elección?",
      "¿Alguna vez has tenido una conversación profunda con un extraño que nunca olvidarás?",
      "Si pudieras aprender instantáneamente cualquier habilidad, ¿cuál sería y cómo la usarías?",
      "¿Tienes alguna historia de viaje emocionante o inusual que te gustaría contar?",
      "Si fueras un personaje de libro o película, ¿cuál sería tu papel en la historia?",
      "¿Alguna vez has tenido un sueño extraño que te hizo reflexionar?",
      "Si pudieras tener una cena con cualquier personaje histórico, ¿qué preguntas les harías?",
      "¿Tienes algún hábito o manía interesante que quieras compartir?",
      "Si pudieras ser parte de cualquier evento deportivo o artístico, ¿cuál sería?",
      "¿Alguna vez has tenido un encuentro con un animal salvaje o exótico?",
      "Si pudieras inventar un nuevo juego, ¿cuál sería la premisa y las reglas?",
      "¿Tienes alguna historia de coincidencia asombrosa que te haya dejado sin palabras?",
      "Si pudieras ser testigo de un descubrimiento científico, ¿cuál elegirías?",
      "¿Alguna vez has tenido un momento en el que te sentiste completamente fuera de tu zona de confort?",
      "Si pudieras viajar en el tiempo y darle un consejo a tu yo más joven, ¿qué le dirías?",
      "¿Tienes alguna experiencia de aprendizaje inusual o inspiradora que quieras compartir?",
      "Si pudieras pasar un día con un personaje de ficción, ¿quién sería y qué harían?",
      "¿Alguna vez has tenido una experiencia mágica que no puedes explicar?",
      "Si pudieras explorar un lugar misterioso o legendario, ¿dónde irías?",
      "¿Tienes una historia de amistad que demuestre la importancia de la confianza?",
      "Si pudieras asistir a un evento histórico, ¿qué momento te gustaría presenciar?",
      "¿Alguna vez has experimentado una conexión instantánea con alguien que acabas de conocer?",
      "Si pudieras crear una nueva festividad, ¿cuál sería su propósito y cómo se celebraría?",
      "¿Tienes alguna historia que demuestre la importancia de seguir tus instintos?"
    ],
  };